const menu = [
    {
      id: 1,
      title: 'Buttermilk Pancakes',
      category: 'Breakfast',
      price: 599,
      img: './images/item-1.jpeg',
      desc: `Fluffy buttermilk pancakes topped with fresh berries and a drizzle of maple syrup. Perfect for a delightful morning start.`,
    },
    {
      id: 2,
      title: 'Diner Double Burger',
      category: 'Lunch',
      price: 499,
      img: './images/item-2.jpeg',
      desc: `A classic double cheeseburger with all the fixings. Juicy beef patties, melted cheese, and a side of crispy fries.`,
    },
    {
      id: 3,
      title: 'Godzilla Milkshake',
      category: 'Shakes',
      price: 299,
      img: './images/item-3.jpeg',
      desc: `A monstrous milkshake packed with cookies, cream, and topped with whipped cream. A true indulgence for shake lovers.`,
    },
    {
      id: 4,
      title: 'Country Delight',
      category: 'Breakfast',
      price: 799,
      img: './images/item-4.jpeg',
      desc: `A hearty breakfast platter featuring farm-fresh eggs, crispy bacon, and golden hash browns. A wholesome country meal.`,
    },
    {
      id: 5,
      title: 'Egg Attack Sandwich',
      category: 'Lunch',
      price: 899,
      img: './images/item-5.jpeg',
      desc: `A gourmet egg sandwich with avocado, bacon, and a spicy aioli. Served on a toasted brioche bun.`,
    },
    {
      id: 6,
      title: 'Oreo Dream Shake',
      category: 'Shakes',
      price: 699,
      img: './images/item-6.jpeg',
      desc: `A creamy shake filled with crushed Oreos, vanilla ice cream, and topped with whipped cream. An Oreo lover's dream.`,
    },
    {
      id: 7,
      title: 'Bacon Overflow',
      category: 'Breakfast',
      price: 399,
      img: './images/item-7.jpeg',
      desc: `Crispy bacon stacked high with scrambled eggs and toast. A breakfast favorite for bacon enthusiasts.`,
    },
    {
      id: 8,
      title: 'American Classic Burger',
      category: 'Lunch',
      price: 599,
      img: './images/item-8.jpeg',
      desc: `An all-American burger with lettuce, tomato, pickles, and a special house sauce. Served with a side of fries.`,
    },
    {
      id: 9,
      title: 'Quarantine Buddy Shake',
      category: 'Shakes',
      price: 649,
      img: './images/item-9.jpeg',
      desc: `A comfort shake with a mix of chocolate and peanut butter, perfect for any time you're craving a sweet treat.`,
    },
  ];
  
  export default menu;
  